# Generated by Django 5.0.7 on 2024-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(blank=True)),
            ],
        ),
    ]
